# Dependencies
markdown:         kramdown
# highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Setup
title:            Vishwanatha HM
tagline:          'Data Scientist/Software Engineer'
description:      'Currently Python Developer @Turing, previously worked at @Flipkart, @SigTuple, @MuSigma.'
url:              https://.vishwanathovi.github.io
baseurl:          /

author:
  name:           'Vishwanatha HM'
  url:            https://twitter.com/wish_wah

paginate:         5
paginate_path: "/blog/page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/vishwanathovi/vishwanathovi.github.io
